[profile.default]
src = "src"
script = "script"
out = "out"
libs = ["lib"]

evm_version = 'cancun'

# Use with: forge script script/DeployRefundProtocol.s.sol:DeployRefundProtocol --rpc-url base --broadcast
[rpc_endpoints]
base = "${BASE_MAINNET_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
